# Generated by Django 4.0.4 on 2022-05-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(max_length=50, verbose_name='CIK')),
                ('ticker', models.CharField(max_length=50, unique=True, verbose_name='Ticker Symbol')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
            ],
        ),
    ]
