# Generated by Django 4.0.4 on 2022-06-04 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=10, verbose_name='Report Type')),
            ],
        ),
        migrations.CreateModel(
            name='AccnNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accn', models.CharField(max_length=50, unique=True, verbose_name='Accn Number')),
                ('filed_date', models.DateField(verbose_name='Filed Date')),
                ('interactive_data', models.BooleanField(default=False)),
                ('cik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.reporttype')),
            ],
        ),
    ]
