# Generated by Django 4.0.4 on 2022-06-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reporttype_accnnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accnnumber',
            name='accn',
            field=models.CharField(max_length=50, verbose_name='Accn Number'),
        ),
    ]
