# Generated by Django 4.0.4 on 2022-06-05 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_accnnumber_accn'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accnnumber',
            unique_together={('accn', 'cik')},
        ),
    ]
