# Generated by Django 4.0.4 on 2022-06-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_accnnumber_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.FloatField()),
                ('statement_field', models.CharField(max_length=1000, unique=True, verbose_name='Statement Field')),
                ('readable_field', models.CharField(max_length=1000, verbose_name='Readable Field')),
                ('statement', models.CharField(choices=[('BS', 'Balance Sheet'), ('I', 'Income'), ('CF', 'Cash Flow')], max_length=2)),
                ('reverse', models.BooleanField(default=False)),
            ],
        ),
    ]
