# Generated by Django 4.0.4 on 2022-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_statementfields_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementfields',
            name='header',
            field=models.CharField(blank=True, choices=[('CA', 'Current assets'), ('NCA', 'Non-current assets'), ('CL', 'Current liabilities'), ('NCL', 'Non-current liabilities'), ('SE', "Stockholders' equity")], max_length=1000, null=True, verbose_name='Header'),
        ),
    ]
